### ISSUE TITLE
portal map does not work on Safari

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2016]
divisions that should be displayed together on the map are not displayed at all
![Screen Shot 2018-03-28 at 09.51.44.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456fb6b7191a378e60c2e50415b4abe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5f34aa984eca5af44ae84457ad113762f43b.png)

**Comment by kiurchv** [comment]
Fixed in #2018

**Comment by svetavedmed** [comment]
still doesn't work
![Screen Shot 2018-04-02 at 17.42.56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f16b7191a379e80c2f53415a48be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5af043e14f57a61a3463f43b.png)

**Comment by svetavedmed** [comment]
fixed on dev
