### ISSUE TITLE
Deduplication process

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#576]
As a NHS Admin
I want to have correct and unique MPI records related to one person
So we have to implement deduplication procedure

Deduplication process [spec](https://edenlab.atlassian.net/wiki/display/EH/Deduplication+process)

- [x] Add table to MPI BD [ERD](https://github.com/Nebo15/ehealth.api/pull/574)
- [x] Implement GET merge_candidate API [spec](http://docs.ehealthapi1.apiary.io/#reference/internal.-master-patients-index/merge-candidates/get-merge-candidates)
- [x] Implement POST merge_candidate API [spec](http://docs.ehealthapi1.apiary.io/#reference/internal.-master-patients-index/merge-candidates/merge-candidate)
- [x] Implement POST Terminate declarations API [spec](http://docs.ehealthapi1.apiary.io/#reference/internal.-ops-db/declarations/terminate-declarations-by-employee-or-person)
- [x] Implement flow according to [spec](https://edenlab.atlassian.net/wiki/display/EH/Deduplication+process)

**Comment by gmile** [comment]
@AlekzandrV according to spec example, we must compare `document` field. But there is no such field in the DB. The is a `documents` (plural) field.

In an example from spec, the field must has a value that looks like a passport, so maybe we should extract passports from both persons under comparison, and compare them?

How should we go about this situation?

**Comment by gmile** [comment]
Core codes are done in https://github.com/Nebo15/ehealth.api/issues/576

**Comment by gmile** [comment]
@AlekzandrV, regarding this:

> Implement POST Terminate declarations API

Why declaration termination logic is part of this ticket?

**Comment by gmile** [comment]
Also, two final items refer to the same spec on Apiary. Is that correct?

**Comment by AlekzandrV** [comment]
@gmile 
> Why is declaration termination logic a part of this ticket?

Because its all about one single story

**Comment by AlekzandrV** [comment]
> Also, two final items refer to the same spec on Apiary. Is that correct?

Fixed

**Comment by gmile** [comment]
REST endpoint `/merge_candidates` was implemented (and merged) in https://github.com/edenlabllc/mpi.api/pull/43

**Comment by gmile** [comment]
The work is being wrapped up in this PR https://github.com/edenlabllc/ehealth.api/pull/751

**Comment by gmile** [comment]
New endpoint on OPS appeared as of https://github.com/edenlabllc/ops.api/pull/12

**Comment by gmile** [comment]
The big PR #751 just got merged. Going to deploy this on dev cluster and start testing.

**Comment by gmile** [comment]
This is now deployed. On dev deduplication will run every minute.

**Comment by lymychp** [comment]
@AlekzandrV please double check that `merged_ids` are fulfilled properly in MPI after merge and search person/declaration works properly

**Comment by AlekzandrV** [comment]
Deduplication error:
1) Following candidates didn't merge:
```
SELECT *
FROM persons
WHERE tax_id = '3067305998'
and birth_date = '2001-08-19'
order by inserted_at;
```

**Comment by gmile** [comment]
Writing `merged_ids`: MPI's part was added in https://github.com/edenlabllc/mpi.api/commit/646c43e98b5dcc94a77d14374f1217f052e31f25

**Comment by gmile** [comment]
> 1. Following candidates didn't merge:

@AlekzandrV for the record, as discussed offline, that issue was fixed. There was, however, a case with a particular candidate not merging. Will investigate separately.

**Comment by AlekzandrV** [comment]
Still the same problem (or another):
There are five records in status NEW in Merge_candidates

Ex. (record IDs)
```
'05d22ebc-ae30-41e1-894c-a47ebcd88578'
'391d469f-9846-4837-ad07-ec9175321d71'
'fc69de0e-1886-4d4c-a47f-7098644d29d4'
'7b944279-502b-445f-b769-5e8a0ea13377'
'7e801e5d-3d85-443d-8e12-bc3c2a054f94'
```
